"""Artifact availability schema.

Generated by ``generate_artifact_availability.py`` → ``artifact_availability.json``.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class PlatformStats(BaseModel):
    """Accessibility stats for a single platform."""

    total: int = Field(ge=0, description="Total URLs checked.")
    accessible: int = Field(ge=0, description="URLs that were accessible.")
    pct: float = Field(ge=0, le=100, description="Accessibility percentage.")

    model_config = {"extra": "forbid"}


class AvailabilitySummary(BaseModel):
    """Aggregate summary of artifact URL accessibility."""

    checked_at: str = Field(description="Timestamp of the check (UTC).")
    total_urls: int = Field(ge=0, description="Total URLs checked.")
    accessible_urls: int = Field(ge=0, description="URLs that were accessible.")
    accessibility_pct: float = Field(ge=0, le=100, description="Overall accessibility percentage.")
    by_platform: dict[str, PlatformStats] = Field(
        description="Stats keyed by hosting platform domain (e.g. 'github.com', 'zenodo.org', 'figshare.com')."
    )
    by_area: dict[str, PlatformStats] = Field(description="Stats keyed by research area ('systems' or 'security').")
    by_year: dict[str, PlatformStats] = Field(description="Stats keyed by publication year as string (e.g. '2023').")
    by_year_area: dict[str, dict[str, PlatformStats]] = Field(
        description="Stats keyed by year (str), then by area ('systems'/'security')."
    )
    by_year_platform: dict[str, dict[str, PlatformStats]] = Field(
        description="Stats keyed by year (str), then by platform domain."
    )
    by_conference: dict[str, PlatformStats] = Field(
        description="Stats keyed by conference abbreviation (e.g. 'OSDI', 'USENIXSEC')."
    )

    model_config = {"extra": "forbid"}


class AvailabilityRecord(BaseModel):
    """Accessibility check result for a single artifact URL."""

    conference: str = Field(description="Conference name.")
    year: int = Field(description="Publication year.")
    area: str = Field(description="Research area.")
    title: str = Field(description="Paper title.")
    url_key: str = Field(description="Key indicating URL type (e.g. 'repository_url').")
    url: str = Field(description="The artifact URL checked.")
    platform: str = Field(description="Detected hosting platform.")
    accessible: bool = Field(description="Whether the URL was accessible.")

    model_config = {"extra": "forbid"}


class ArtifactAvailability(BaseModel):
    """Artifact URL accessibility report: aggregate summary and per-URL check results."""

    summary: AvailabilitySummary = Field(description="Aggregate accessibility summary.")
    records: list[AvailabilityRecord] = Field(description="Per-URL check results.")

    model_config = {"extra": "forbid"}
