"""Artifact citation schema.

Generated by ``generate_artifact_citations.py`` → ``artifact_citations.json``.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class ArtifactCitation(BaseModel):
    """Citation data for a single artifact DOI."""

    title: str = Field(description="Paper title.")
    conference: str = Field(description="Conference name.")
    year: int = Field(description="Publication year.")
    doi: str = Field(default="", description="Artifact DOI (empty if not found).")
    doi_source: str = Field(default="", description="Source of the DOI (e.g. 'zenodo').")
    cited_by_count: int | None = Field(
        default=None, description="Aggregate citation count (best of OpenAlex/Semantic Scholar)."
    )
    citations_openalex: int | None = Field(default=None, description="Citation count from OpenAlex.")
    citations_semantic_scholar: int | None = Field(default=None, description="Citation count from Semantic Scholar.")
    citing_dois_openalex: list[str] = Field(default_factory=list, description="DOIs of citing works from OpenAlex.")
    citing_dois_semantic_scholar: list[str] = Field(
        default_factory=list, description="DOIs of citing works from Semantic Scholar."
    )

    model_config = {"extra": "forbid"}
