"""Artifact collection schema.

Generated by ``generate_statistics.py`` → ``artifacts.json``.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, field_validator

CONFERENCE_NAMES = Literal[
    "ACSAC",
    "ATC",
    "CHES",
    "EUROSYS",
    "FAST",
    "NDSS",
    "OSDI",
    "PETS",
    "SC",
    "SOSP",
    "SYSTEX",
    "USENIXSEC",
    "WOOT",
]

CATEGORY = Literal["systems", "security"]


class Artifact(BaseModel):
    """A single research artifact associated with a conference paper."""

    conference: CONFERENCE_NAMES = Field(
        description="Conference abbreviation where the paper was published.",
    )
    category: CATEGORY = Field(
        description="Research domain category.",
    )
    year: int = Field(
        ge=2017,
        le=2030,
        description="Publication year.",
    )
    title: str = Field(
        description="Paper title.",
    )
    badges: list[str] = Field(
        description=(
            "Artifact evaluation badges. Canonical values: 'available', "
            "'functional', 'reproduced', 'reusable', 'replicated'. "
            "Some conferences use non-normalized variants."
        ),
    )
    artifact_urls: list[str] = Field(
        description=(
            "All artifact-related URLs (repositories, archives, DOIs). "
            "Canonical field replacing repository_url, artifact_url, and github_url."
        ),
    )
    doi: str = Field(
        default="",
        description="Canonical artifact DOI (e.g. '10.5281/zenodo.12345'). Extracted from artifact_urls.",
    )
    paper_url: str | None = Field(
        default=None,
        description="DOI or direct link to the published paper.",
    )
    appendix_url: str | None = Field(
        default=None,
        description="URL to supplementary materials or appendix.",
    )
    award: str | None = Field(
        default=None,
        description="Award designation, if any (e.g., 'Distinguished Artifact').",
    )

    @field_validator("award", mode="before")
    @classmethod
    def _coerce_award(cls, v: object) -> str | None:
        if isinstance(v, bool):
            return str(v).lower()
        return v  # type: ignore[return-value]

    model_config = {"extra": "forbid"}


class ArtifactCollection(BaseModel):
    """Collection of research artifacts from systems and security conferences.

    Generated by the ReproDB pipeline.
    Written as ``artifacts.json`` in ``assets/data/``.
    """

    root: list[Artifact]

    @classmethod
    def json_schema(cls) -> dict:
        return Artifact.model_json_schema()
