"""Artifacts by year schema.

Generated by ``generate_statistics.py`` → ``artifacts_by_year.yml``.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class ArtifactsByYear(BaseModel):
    """Artifact count for a single year with systems/security breakdown."""

    year: int = Field(description="Publication year.")
    count: int = Field(ge=0, description="Total artifacts for this year.")
    systems: int = Field(ge=0, description="Artifacts from systems conferences.")
    security: int = Field(ge=0, description="Artifacts from security conferences.")

    model_config = {"extra": "forbid"}
