"""Artifacts by conference schema.

Generated by ``generate_statistics.py`` → ``artifacts_by_conference.yml``.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class YearBreakdown(BaseModel):
    """Per-year breakdown of artifact counts and badges."""

    year: int = Field(description="Publication year.")
    total: int = Field(ge=0, description="Total artifacts for this conference-year.")
    available: int = Field(ge=0, description="Count of 'available' badges.")
    functional: int = Field(ge=0, description="Count of 'functional' badges.")
    reproducible: int = Field(ge=0, description="Count of 'reproduced' badges.")
    reusable: int = Field(ge=0, description="Count of 'reusable' badges.")

    model_config = {"extra": "forbid"}


class ConferenceEntry(BaseModel):
    """Artifact counts and badge breakdowns for a single conference."""

    name: str = Field(description="Conference abbreviation.")
    category: Literal["systems", "security"] = Field(description="Research domain.")
    venue_type: Literal["conference", "workshop"] = Field(
        description="Whether this is a full conference or a workshop.",
    )
    total_artifacts: int = Field(ge=0, description="Total artifacts across all years.")
    years: list[YearBreakdown] = Field(description="Per-year breakdown of artifact counts and badges.")

    model_config = {"extra": "forbid"}
