"""Author profile schema.

Generated by ``generate_author_stats.py`` → ``author_profiles.json``.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class AuthorProfile(BaseModel):
    """Profile data for a single author combining publications and AE service."""

    name: str = Field(description="Full author name (may include DBLP disambiguation suffix).")
    affiliation: str = Field(description="Current institutional affiliation.")
    papers: list[dict] = Field(description="List of paper entries associated with this author.")
    papers_without_artifacts: list[dict] = Field(
        default_factory=list, description="Papers by this author that do not have artifacts."
    )
    conferences: list[list] | list[str] = Field(
        description="Conferences: list of [conference, year, role] tuples (AE-only) or conference name strings."
    )
    years: list[int] | dict[str, int] = Field(description="Years of activity (list of years or year → count mapping).")
    artifact_count: int = Field(ge=0, description="Number of artifacts authored.")
    total_papers: int = Field(ge=0, description="Total papers at tracked conferences.")
    artifact_pct: float = Field(ge=0, le=100, description="Percentage of papers with artifacts.")
    artifact_citations: int = Field(ge=0, description="Total artifact citations.")
    badges_available: int = Field(ge=0, description="Count of 'available' badges.")
    badges_functional: int = Field(ge=0, description="Count of 'functional' badges.")
    badges_reproducible: int = Field(ge=0, description="Count of 'reproduced' badges.")
    category: str = Field(description="Author category based on contribution profile.")
    ae_memberships: int = Field(default=0, ge=0, description="Number of AE committee memberships.")
    chair_count: int = Field(default=0, ge=0, description="Number of AE chair roles.")
    ae_conferences: list[list] = Field(
        default_factory=list, description="List of [conference, year, role] tuples for AE service."
    )
    ae_years: dict[str, int] | list[int] = Field(default_factory=dict, description="AE years (dict or list).")
    combined_score: int = Field(ge=0, description="Total combined score.")
    artifact_score: int = Field(ge=0, description="Points from artifacts.")
    citation_score: int = Field(ge=0, description="Points from citations.")
    ae_score: int = Field(ge=0, description="Points from AE service.")
    rank: int | None = Field(default=None, ge=1, description="Ranking position.")
    author_id: int | None = Field(default=None, ge=1, description="Stable integer identifier.")

    model_config = {"extra": "forbid"}
