"""Author profile schema.

Generated by ``generate_author_profiles.py`` → ``author_profiles.json``.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, field_validator

from src.models.ae_members import AEMembership
from src.models.author_stats import ArtifactPaper, PlainPaper


class AuthorProfile(BaseModel):
    """Profile data for a single author combining publications and AE service.

    Generated by ``generate_author_profiles.py`` by merging data from
    ``authors.json``, ``ae_members.json``, and ``combined_rankings.json``.
    """

    name: str = Field(description="Full author name (may include DBLP disambiguation suffix).")
    affiliation: str = Field(description="Current institutional affiliation.")
    papers: list[ArtifactPaper] = Field(
        default_factory=list,
        description="Artifact papers authored. Each has title, conference, year, badges, category, artifact_citations.",
    )
    papers_without_artifacts: list[PlainPaper] = Field(
        default_factory=list,
        description="Papers by this author that do not have artifacts.",
    )
    conferences: list[str] = Field(
        description="Conference abbreviations where author has published or served on AE.",
    )
    years: list[int] = Field(description="Sorted list of years with activity.")
    artifact_count: int = Field(ge=0, description="Number of artifacts authored.")
    total_papers: int = Field(ge=0, description="Total papers at tracked conferences.")
    artifact_pct: float = Field(ge=0, le=100, description="Percentage of papers with artifacts.")
    artifact_citations: int = Field(ge=0, description="Total artifact citations.")
    badges_available: int = Field(ge=0, description="Count of 'available' badges.")
    badges_functional: int = Field(ge=0, description="Count of 'functional' badges.")
    badges_reproducible: int = Field(ge=0, description="Count of 'reproduced' badges.")
    category: Literal["systems", "security", "both"] = Field(
        description="Research domain based on conferences published at or served on AE.",
    )
    ae_memberships: int = Field(default=0, ge=0, description="Number of AE committee memberships.")
    chair_count: int = Field(default=0, ge=0, description="Number of AE chair roles.")
    ae_conferences: list[AEMembership] = Field(
        default_factory=list,
        description="AE committee memberships, one per conference-year served.",
    )
    ae_years: dict[str, int] = Field(
        default_factory=dict,
        description="Year (as string, e.g. '2023') → number of AE memberships that year.",
    )
    combined_score: int = Field(ge=0, description="Total combined score.")
    artifact_score: int = Field(ge=0, description="Points from artifacts.")
    citation_score: int = Field(ge=0, description="Points from citations.")
    ae_score: int = Field(ge=0, description="Points from AE service.")
    rank: int | None = Field(default=None, ge=1, description="Ranking position.")
    author_id: int | None = Field(default=None, ge=1, description="Stable integer identifier.")

    @field_validator("conferences", mode="before")
    @classmethod
    def _coerce_conferences(cls, v: object) -> object:
        """Accept [conf, year, role] tuples and extract conference name strings."""
        if isinstance(v, list) and v and isinstance(v[0], (list, tuple)):
            seen: set[str] = set()
            result: list[str] = []
            for item in v:
                name = item[0] if isinstance(item, (list, tuple)) else item
                if name not in seen:
                    seen.add(name)
                    result.append(name)
            return result
        return v

    @field_validator("ae_conferences", mode="before")
    @classmethod
    def _coerce_ae_conferences(cls, v: object) -> object:
        """Accept both [conf, year, role] lists and {conference, year, role} dicts."""
        if isinstance(v, list):
            return [
                {"conference": item[0], "year": item[1], "role": item[2]} if isinstance(item, (list, tuple)) else item
                for item in v
            ]
        return v

    model_config = {"extra": "forbid"}
