"""Author statistics schema.

Generated by ``generate_author_stats.py`` → ``authors.json``, ``authors.yml``.
Variants: ``systems_authors.yml``, ``security_authors.yml``.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class ArtifactPaper(BaseModel):
    """A paper that has an associated artifact evaluation."""

    title: str = Field(description="Paper title.")
    conference: str = Field(description="Conference abbreviation.")
    year: int = Field(description="Publication year.")
    badges: list[str] = Field(
        description=(
            "Artifact evaluation badges. Canonical values: 'available', "
            "'functional', 'reproduced', 'reusable', 'replicated'."
        ),
    )
    category: Literal["systems", "security"] = Field(description="Research domain.")
    artifact_citations: int = Field(ge=0, description="Citation count for this artifact.")

    model_config = {"extra": "forbid"}


class PlainPaper(BaseModel):
    """A published paper without an artifact evaluation."""

    title: str = Field(description="Paper title.")
    conference: str = Field(description="Conference abbreviation.")
    year: int = Field(description="Publication year.")

    model_config = {"extra": "forbid"}


class AuthorCore(BaseModel):
    """Common author fields shared by per-author statistics and profile records."""

    name: str = Field(description="Full name in DBLP format (may include disambiguation suffix).")
    affiliation: str = Field(description="Normalized institution affiliation.")
    papers: list[ArtifactPaper] = Field(
        default_factory=list,
        description="Artifact papers authored.",
    )
    papers_without_artifacts: list[PlainPaper] = Field(
        default_factory=list,
        description="Papers by this author that do not have artifacts.",
    )
    conferences: list[str] = Field(description="Conference abbreviations where author has published.")
    years: list[int] = Field(description="Sorted list of years with activity.")
    artifact_count: int = Field(ge=0, description="Total artifacts authored.")
    total_papers: int = Field(ge=0, description="Total papers at tracked conferences.")
    artifact_pct: float = Field(ge=0, le=100, description="Percentage of papers with artifacts.")
    artifact_citations: int = Field(ge=0, description="Total citation count for artifacts.")
    badges_available: int = Field(ge=0, description="Count of 'available' badges across all artifacts.")
    badges_functional: int = Field(ge=0, description="Count of 'functional' badges across all artifacts.")
    badges_reproducible: int = Field(ge=0, description="Count of 'reproduced' badges across all artifacts.")
    category: Literal["systems", "security", "both"] = Field(
        description="Research domain based on conferences published at.",
    )
    author_id: int | None = Field(
        default=None,
        ge=1,
        description="Stable integer identifier referencing the canonical author_index.",
    )

    model_config = {"extra": "forbid"}


class AuthorStats(AuthorCore):
    """Per-author artifact statistics including badge counts, paper breakdowns, and conference history."""

    display_name: str = Field(description="Name without DBLP disambiguation suffix.")
    total_papers_by_conf: dict[str, int] = Field(
        description="Mapping of conference name to paper count at that conference.",
    )
    total_papers_by_conf_year: dict[str, dict[str, int]] = Field(
        description="Nested mapping: conference name → { year → count }.",
    )
    repro_pct: float = Field(ge=0, le=100, description="Percentage of artifacts with a reproducibility badge.")
    functional_pct: float = Field(ge=0, le=100, description="Percentage of artifacts with a functional badge.")
    category: Literal["systems", "security", "both", "unknown"] = Field(  # type: ignore[assignment]
        description="Research domain based on conferences published at.",
    )
    year_range: str = Field(pattern=r"^\d{4}-\d{4}$", description="Activity range in 'YYYY-YYYY' format.")
    recent_count: int = Field(ge=0, description="Number of papers in the last 3 years.")
    paper_ids: list[int] = Field(
        default_factory=list,
        description="List of paper index IDs for artifact papers. References papers.json.",
    )
    papers_without_artifact_ids: list[int] = Field(
        default_factory=list,
        description="List of paper index IDs for non-artifact papers. References papers.json.",
    )

    model_config = {"extra": "forbid"}
