"""Author profile schema.

Generated by ``generate_author_profiles.py`` → ``author_profiles.json``.
"""

from __future__ import annotations

from pydantic import Field, field_validator

from src.models.ae_members import AEMembership
from src.models.author_stats import AuthorCore


class AuthorProfile(AuthorCore):
    """Unified author profile combining publication record, artifact metrics, and AE committee service."""

    ae_memberships: int = Field(default=0, ge=0, description="Number of AE committee memberships.")
    chair_count: int = Field(default=0, ge=0, description="Number of AE chair roles.")
    ae_conferences: list[AEMembership] = Field(
        default_factory=list,
        description="AE committee memberships, one per conference-year served.",
    )
    ae_years: dict[str, int] = Field(
        default_factory=dict,
        description="Year (as string, e.g. '2023') → number of AE memberships that year.",
    )
    combined_score: int = Field(ge=0, description="Total combined score.")
    artifact_score: int = Field(ge=0, description="Points from artifacts.")
    citation_score: int = Field(ge=0, description="Points from citations.")
    ae_score: int = Field(ge=0, description="Points from AE service.")
    rank: int | None = Field(default=None, ge=1, description="Ranking position.")

    @field_validator("conferences", mode="before")
    @classmethod
    def _coerce_conferences(cls, v: object) -> object:
        """Accept [conf, year, role] tuples and extract conference name strings."""
        if isinstance(v, list) and v and isinstance(v[0], (list, tuple)):
            seen: set[str] = set()
            result: list[str] = []
            for item in v:
                name = item[0] if isinstance(item, (list, tuple)) else item
                if name not in seen:
                    seen.add(name)
                    result.append(name)
            return result
        return v

    @field_validator("ae_conferences", mode="before")
    @classmethod
    def _coerce_ae_conferences(cls, v: object) -> object:
        """Accept both [conf, year, role] lists and {conference, year, role} dicts."""
        if isinstance(v, list):
            return [
                {"conference": item[0], "year": item[1], "role": item[2]} if isinstance(item, (list, tuple)) else item
                for item in v
            ]
        return v
