"""Committee statistics schema.

Generated by ``generate_committee_stats.py`` → ``committee_stats.json``.
Variants: ``systems_committee_stats.json``, ``security_committee_stats.json``.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class NameCount(BaseModel):
    """A simple name/count pair used for country, continent, and institution tallies."""

    name: str = Field(description="Country, continent, or institution name.")
    count: int = Field(ge=0, description="Member count.")

    model_config = {"extra": "forbid"}


class CommitteeSummary(BaseModel):
    """Aggregate committee summary statistics."""

    total_members: int = Field(ge=0, description="Total committee members across all years.")
    total_systems: int = Field(ge=0, description="Members from systems conferences.")
    total_security: int = Field(ge=0, description="Members from security conferences.")
    total_countries: int = Field(ge=0, description="Unique countries represented.")
    total_continents: int = Field(ge=0, description="Unique continents represented.")
    total_institutions: int = Field(ge=0, description="Unique institutions represented.")

    model_config = {"extra": "forbid"}


class CommitteeSize(BaseModel):
    """Committee size for a single conference-year."""

    conference: str = Field(description="Conference name.")
    year: int = Field(description="Year.")
    conf_year: str = Field(description="Combined conference-year key (e.g. 'acsac2017').")
    area: str = Field(description="Research area: 'systems' or 'security'.")
    size: int = Field(ge=0, description="Number of committee members.")

    model_config = {"extra": "forbid"}


class FailedClassification(BaseModel):
    """A committee member whose institution could not be geolocated."""

    conference: str = Field(description="Conference-year key.")
    name: str = Field(description="Member name.")
    affiliation: str = Field(description="Raw affiliation string that failed lookup.")

    model_config = {"extra": "forbid"}


class SplitCounts(BaseModel):
    """Country/institution counts split by overall/systems/security."""

    overall: list[NameCount] = Field(description="Overall counts.")
    systems: list[NameCount] = Field(description="Systems-only counts.")
    security: list[NameCount] = Field(description="Security-only counts.")

    model_config = {"extra": "forbid"}


class CommitteeStats(BaseModel):
    """AE committee geographic and institutional diversity: country, continent, and institution breakdowns."""

    summary: CommitteeSummary = Field(description="Aggregate summary.")
    by_country: SplitCounts = Field(description="Member counts by country.")
    by_continent: SplitCounts = Field(description="Member counts by continent.")
    by_institution: SplitCounts = Field(description="Member counts by institution.")
    by_year: dict[str, dict[str, dict[str, int]]] = Field(
        description="Year-level breakdowns keyed by category (e.g. 'country', 'continent'),"
        " then year, then name → count."
    )
    committee_sizes: list[CommitteeSize] = Field(description="Committee sizes per conference-year.")
    failed_classifications: list[FailedClassification] = Field(
        description="Members whose affiliation could not be geolocated."
    )

    model_config = {"extra": "forbid"}
