"""Committee statistics schema.

Generated by ``generate_committee_stats.py`` → ``committee_stats.json``.
Variants: ``systems_committee_stats.json``, ``security_committee_stats.json``.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class NameCount(BaseModel):
    """A simple name/count pair used for country, continent, and institution tallies."""

    name: str = Field(
        description="Country, continent, or institution name, e.g. 'United States', 'Europe', 'MIT'.",
        examples=["Mathias Payer"],
    )
    count: int = Field(ge=0, description="Number of AE committee members from this entity.", examples=[127])

    model_config = {"extra": "forbid"}


class CommitteeSummary(BaseModel):
    """Aggregate committee summary statistics."""

    total_members: int = Field(
        ge=0,
        description="Total AE committee members across all conferences and years (includes duplicates for multi-year service).",
        examples=[1250],
    )
    total_systems: int = Field(
        ge=0,
        description="Committee members from systems conferences (ATC, EUROSYS, FAST, OSDI, SC, SOSP).",
        examples=[600],
    )
    total_security: int = Field(
        ge=0,
        description="Committee members from security conferences (ACSAC, CHES, NDSS, PETS, SYSTEX, USENIXSEC, WOOT).",
        examples=[650],
    )
    total_countries: int = Field(
        ge=0,
        description="Number of unique countries represented across all committees, e.g. 59.",
        examples=[35],
    )
    total_continents: int = Field(ge=0, description="Number of unique continents represented, e.g. 7.", examples=[6])
    total_institutions: int = Field(
        ge=0, description="Number of unique institutions represented, e.g. 470.", examples=[280]
    )

    model_config = {"extra": "forbid"}


class CommitteeSize(BaseModel):
    """Committee size for a single conference-year."""

    conference: str = Field(description="Conference abbreviation, e.g. 'ACSAC', 'OSDI'.", examples=["osdi2023"])
    year: int = Field(description="Calendar year, e.g. 2023.", examples=[2023])
    conf_year: str = Field(
        description="Combined lowercase conference-year key, e.g. 'acsac2017', 'osdi2023'.", examples=["osdi2023"]
    )
    area: str = Field(description="Research area of this conference: 'systems' or 'security'.", examples=["systems"])
    size: int = Field(ge=0, description="Number of AE committee members for this conference-year.", examples=[25])

    model_config = {"extra": "forbid"}


class FailedClassification(BaseModel):
    """A committee member whose institution could not be geolocated."""

    conference: str = Field(description="Conference abbreviation, e.g. 'ATC', 'USENIXSEC'.", examples=["osdi2023"])
    name: str = Field(
        description="Full name of the committee member whose affiliation could not be resolved.",
        examples=["Mathias Payer"],
    )
    affiliation: str = Field(
        description="Raw affiliation string that could not be geolocated or matched to an institution.",
        examples=["ETH Zurich"],
    )

    model_config = {"extra": "forbid"}


class SplitCounts(BaseModel):
    """Country/institution counts split by overall/systems/security."""

    overall: list[NameCount] = Field(description="Counts combining all areas (systems + security).")
    systems: list[NameCount] = Field(description="Counts from systems conferences only.", examples=[75])
    security: list[NameCount] = Field(description="Counts from security conferences only.", examples=[52])

    model_config = {"extra": "forbid"}


class CommitteeStats(BaseModel):
    """AE committee geographic and institutional diversity: country, continent, and institution breakdowns."""

    summary: CommitteeSummary = Field(
        description="Aggregate summary with totals for members, countries, continents, and institutions."
    )
    by_country: SplitCounts = Field(
        description="Member counts by country, split into overall/systems/security. e.g. 'United States': 2103."
    )
    by_continent: SplitCounts = Field(description="Member counts by continent, split into overall/systems/security.")
    by_institution: SplitCounts = Field(
        description="Member counts by institution, split into overall/systems/security."
    )
    by_year: dict[str, dict[str, dict[str, int]]] = Field(
        description="Year-level geographic/institutional breakdowns keyed by category (e.g. 'country', 'continent'),"
        " then year, then name → count."
    )
    committee_sizes: list[CommitteeSize] = Field(
        description="Committee sizes for each conference-year. One entry per conference-year combination."
    )
    failed_classifications: list[FailedClassification] = Field(
        description="Members whose affiliation string could not be resolved to a country/institution."
    )

    model_config = {"extra": "forbid"}
