"""Institution ranking history schema.

Generated by ``generate_combined_rankings.py`` → ``institution_ranking_history.json``.
Variants: ``systems_institution_ranking_history.json``, ``security_institution_ranking_history.json``.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class InstitutionRankingSnapshot(BaseModel):
    """A single institution's ranking at a point in time."""

    rank: int = Field(ge=1, description="Ranking position.")
    score: int = Field(ge=0, description="Combined score.")
    as_: int = Field(alias="as", ge=0, description="Artifact score.")
    aes: int = Field(ge=0, description="AE service score.")
    tp: int = Field(ge=0, description="Total papers.")
    ta: int = Field(ge=0, description="Total artifacts.")
    ar: float = Field(ge=0, le=100, description="Artifact rate (%).")
    rr: float = Field(ge=0, le=100, description="Reproducibility rate (%).")
    r: int = Field(ge=0, description="Number of unique researchers.")

    model_config = {"extra": "forbid", "populate_by_name": True}


class InstitutionRankingHistoryEntry(BaseModel):
    """A dated snapshot of all institution rankings."""

    date: str = Field(description="ISO date string (YYYY-MM-DD) of the snapshot.")
    entries: dict[str, InstitutionRankingSnapshot] = Field(description="Institution name → ranking snapshot mapping.")

    model_config = {"extra": "forbid"}
