"""Paper citation schema.

Generated by ``generate_paper_citations.py`` → ``paper_citations.json``.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class PaperCitation(BaseModel):
    """Citation data for a single paper via Google Scholar."""

    title: str = Field(description="Paper title.")
    normalized_title: str = Field(description="Lowercased, stripped title for deduplication.")
    conference: str = Field(description="Conference name.")
    year: int = Field(description="Publication year.")
    category: str = Field(default="", description="Paper category/track.")
    badges: str = Field(default="", description="Comma-separated badge names.")
    cited_by_count: int | None = Field(default=None, description="Citation count from Google Scholar.")
    source: str = Field(default="", description="Source used for lookup (e.g. 'scholar').")
    error: str | None = Field(default=None, description="Error message if lookup failed.")

    model_config = {"extra": "forbid"}
