"""Paper citation schema (DOI-based, via OpenAlex / Semantic Scholar).

Generated by ``generate_paper_citations_doi.py`` → ``_build/paper_citations.json``.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class PaperCitationDoi(BaseModel):
    """Citation data for a single paper looked up by DOI."""

    title: str = Field(description="Paper title.")
    normalized_title: str = Field(description="Lowercased, stripped title for deduplication.")
    conference: str = Field(description="Conference name.")
    year: int = Field(description="Publication year.")
    category: str = Field(default="", description="Research domain category.")
    paper_doi: str = Field(default="", description="Paper DOI used for lookup.")
    openalex_id: str = Field(default="", description="OpenAlex work ID (e.g. https://openalex.org/W…).")
    cited_by_count: int | None = Field(
        default=None, description="Best citation count (max of OpenAlex/Semantic Scholar)."
    )
    citations_openalex: int | None = Field(default=None, description="Citation count from OpenAlex.")
    citations_semantic_scholar: int | None = Field(default=None, description="Citation count from Semantic Scholar.")
    source: str = Field(default="", description="Lookup method (openalex_doi, openalex_title).")

    model_config = {"extra": "forbid"}
