"""Participation statistics schema.

Generated by ``generate_participation_stats.py`` → ``participation_stats.json``.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class ConferenceYearStats(BaseModel):
    """Participation stats for a single conference-year."""

    conference: str = Field(description="Conference name.")
    year: int = Field(description="Year.")
    category: str = Field(description="Paper category/track.")
    venue_type: str = Field(description="Venue type: 'conference' or 'workshop'.")
    total_papers: int = Field(ge=0, description="Total papers in this conference-year.")
    ae_papers: int = Field(ge=0, description="Papers submitted to the AE process.")
    participation_pct: float = Field(ge=0, le=100, description="AE participation rate (%).")
    available: int = Field(ge=0, description="Papers with 'available' badge.")
    functional: int = Field(ge=0, description="Papers with 'functional' badge.")
    reproduced: int = Field(ge=0, description="Papers with 'reproduced' badge.")
    available_pct: float = Field(ge=0, le=100, description="Available rate (%).")
    functional_pct: float = Field(ge=0, le=100, description="Functional rate (%).")
    reproduced_pct: float = Field(ge=0, le=100, description="Reproduced rate (%).")

    model_config = {"extra": "forbid"}


class AreaTrend(BaseModel):
    """Trend data for a research area over time."""

    years: list[int] = Field(description="List of years in chronological order.")
    participation_pct: list[float] = Field(description="Participation rate per year.")
    available_pct: list[float] = Field(description="Available rate per year.")
    functional_pct: list[float] = Field(description="Functional rate per year.")
    reproduced_pct: list[float] = Field(description="Reproduced rate per year.")

    model_config = {"extra": "forbid"}


class ParticipationStats(BaseModel):
    """Top-level participation statistics output."""

    by_conference_year: list[ConferenceYearStats] = Field(description="Per-conference-year breakdown.")
    by_area: dict[str, AreaTrend] = Field(description="Trend data keyed by area name ('security', 'systems').")

    model_config = {"extra": "forbid"}
