"""Participation statistics schema.

Generated by ``generate_participation_stats.py`` → ``participation_stats.json``.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class ConferenceYearStats(BaseModel):
    """Participation stats for a single conference-year."""

    conference: str = Field(description="Conference abbreviation, e.g. 'ACSAC', 'OSDI', 'USENIXSEC'.")
    year: int = Field(description="Calendar year, e.g. 2023.")
    category: str = Field(description="Research area category: 'systems' or 'security'.")
    venue_type: str = Field(
        description="Venue type: 'conference' for main conferences, 'workshop' for co-located workshops."
    )
    total_papers: int = Field(
        ge=0, description="Total accepted papers in this conference-year (including those without artifacts)."
    )
    ae_papers: int = Field(ge=0, description="Number of papers that participated in the artifact evaluation process.")
    participation_pct: float = Field(
        ge=0, le=100, description="AE participation rate: (ae_papers / total_papers) * 100."
    )
    available: int = Field(ge=0, description="Number of papers that received the 'available' badge.")
    functional: int = Field(ge=0, description="Number of papers that received the 'functional' badge.")
    reproduced: int = Field(ge=0, description="Number of papers that received the 'reproduced' badge.")
    available_pct: float = Field(
        ge=0, le=100, description="Percentage of total papers with 'available' badge: (available / total_papers) * 100."
    )
    functional_pct: float = Field(
        ge=0,
        le=100,
        description="Percentage of total papers with 'functional' badge: (functional / total_papers) * 100.",
    )
    reproduced_pct: float = Field(
        ge=0,
        le=100,
        description="Percentage of total papers with 'reproduced' badge: (reproduced / total_papers) * 100.",
    )

    model_config = {"extra": "forbid"}


class AreaTrend(BaseModel):
    """Trend data for a research area over time."""

    years: list[int] = Field(description="List of years in chronological order, e.g. [2017, 2018, ..., 2026].")
    participation_pct: list[float] = Field(
        description="AE participation rate per year (%), parallel to the years list."
    )
    available_pct: list[float] = Field(description="Available badge rate per year (%), parallel to the years list.")
    functional_pct: list[float] = Field(description="Functional badge rate per year (%), parallel to the years list.")
    reproduced_pct: list[float] = Field(description="Reproduced badge rate per year (%), parallel to the years list.")

    model_config = {"extra": "forbid"}


class ParticipationStats(BaseModel):
    """Artifact evaluation participation rates per conference-year, with area-level trends over time."""

    by_conference_year: list[ConferenceYearStats] = Field(
        description="Per-conference-year breakdown with paper counts and badge statistics."
    )
    by_area: dict[str, AreaTrend] = Field(
        description="Trend data keyed by area: 'security' and 'systems'. Each has parallel year/rate arrays."
    )

    model_config = {"extra": "forbid"}
