"""Ranking history schema.

Generated by ``generate_combined_rankings.py`` → ``ranking_history.json``.
Variants: ``systems_ranking_history.json``, ``security_ranking_history.json``.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class RankingSnapshot(BaseModel):
    """A single author's ranking at a point in time."""

    rank: int = Field(ge=1, description="Ranking position.")
    score: int = Field(ge=0, description="Combined score.")
    # Abbreviated field names match the JS frontend expectations.
    as_: int = Field(alias="as", ge=0, description="Artifact score.")
    aes: int = Field(ge=0, description="AE service score.")
    tp: int = Field(ge=0, description="Total papers.")
    ta: int = Field(ge=0, description="Total artifacts.")
    ar: float = Field(ge=0, le=100, description="Artifact rate (%).")
    rr: float = Field(ge=0, le=100, description="Reproducibility rate (%).")

    model_config = {"extra": "forbid", "populate_by_name": True}


class RankingHistoryEntry(BaseModel):
    """Dated snapshot of all author rankings, enabling rank-over-time analysis."""

    date: str = Field(description="ISO date string (YYYY-MM-DD) of the snapshot.")
    entries: dict[str, RankingSnapshot] = Field(description="Author name → ranking snapshot mapping.")

    model_config = {"extra": "forbid"}
