"""Yearly repository statistics schema.

Generated by ``generate_repo_stats.py`` → ``repo_stats_yearly.json``.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class YearlyRepoMetrics(BaseModel):
    """Aggregate GitHub metrics for a group of repositories in a given year."""

    github_repos: int = Field(ge=0, description="Number of repositories.")
    avg_stars: float = Field(ge=0, description="Average star count.")
    avg_forks: float = Field(ge=0, description="Average fork count.")
    min_stars: float = Field(ge=0, description="Minimum star count.")
    max_stars: float = Field(ge=0, description="Maximum star count.")
    min_forks: float = Field(ge=0, description="Minimum fork count.")
    max_forks: float = Field(ge=0, description="Maximum fork count.")

    model_config = {"extra": "forbid"}


class RepoStatsYearly(BaseModel):
    """Yearly repository statistics split by area (all, systems, security) with aggregate GitHub metrics."""

    year: int = Field(description="Year.")
    all: YearlyRepoMetrics = Field(description="Combined metrics across all areas.")
    systems: YearlyRepoMetrics | None = Field(
        default=None, description="Systems-only metrics (absent if no systems data for this year)."
    )
    security: YearlyRepoMetrics | None = Field(
        default=None, description="Security-only metrics (absent if no security data for this year)."
    )

    model_config = {"extra": "forbid"}
