"""Repository statistics schemas.

Generated by ``generate_repo_stats.py``.
- Detail: ``repo_stats.json``
- Summary: ``repo_stats.yml``
"""

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field


# ── Detail (per-artifact) ──────────────────────────────────────────


class RepoStatsEntry(BaseModel):
    """Repository metrics for a single artifact."""

    conference: str = Field(description="Conference abbreviation.")
    year: int = Field(description="Publication year.")
    title: str = Field(description="Paper title.")
    url: str = Field(description="Repository or archive URL.")
    source: Literal["github", "zenodo", "figshare"] = Field(
        description="Platform hosting the artifact.",
    )
    github_stars: Optional[int] = Field(default=None, ge=0, description="GitHub star count.")
    github_forks: Optional[int] = Field(default=None, ge=0, description="GitHub fork count.")
    zenodo_views: Optional[int] = Field(default=None, ge=0, description="Zenodo view count.")
    zenodo_downloads: Optional[int] = Field(default=None, ge=0, description="Zenodo download count.")
    description: Optional[str] = Field(
        default=None, max_length=120,
        description="Repository description (truncated to 120 characters).",
    )
    language: Optional[str] = Field(default=None, description="Primary programming language.")
    name: Optional[str] = Field(default=None, description="Repository identifier (e.g., 'owner/repo').")
    pushed_at: Optional[str] = Field(default=None, description="Timestamp of last push in ISO 8601 format.")

    model_config = {"extra": "forbid"}


# ── Summary (aggregated) ──────────────────────────────────────────


class TopRepo(BaseModel):
    """A top repository within a conference."""

    name: Optional[str] = Field(default=None)
    url: Optional[str] = Field(default=None)
    stars: Optional[int] = Field(default=None, ge=0)
    forks: Optional[int] = Field(default=None, ge=0)
    language: Optional[str] = Field(default=None)
    description: Optional[str] = Field(default=None)


class ConferenceYearStats(BaseModel):
    """Repository metrics for a single conference-year."""

    year: int
    github_repos: int = Field(ge=0)
    total_stars: int = Field(ge=0)
    total_forks: int = Field(ge=0)
    avg_stars: float = Field(ge=0)
    avg_forks: float = Field(ge=0)


class ConferenceRepoStats(BaseModel):
    """Repository metrics grouped by conference."""

    name: str
    github_repos: int = Field(ge=0)
    total_stars: int = Field(ge=0)
    total_forks: int = Field(ge=0)
    avg_stars: float = Field(ge=0)
    avg_forks: float = Field(ge=0)
    max_stars: int = Field(ge=0)
    max_forks: int = Field(ge=0)
    years: list[ConferenceYearStats] = Field(default_factory=list)
    top_repos: list[TopRepo] = Field(default_factory=list)

    model_config = {"extra": "forbid"}


class YearRepoStats(BaseModel):
    """Repository metrics grouped by year."""

    year: int
    github_repos: int = Field(ge=0)
    total_stars: int = Field(ge=0)
    total_forks: Optional[int] = Field(default=None, ge=0)
    avg_stars: Optional[float] = Field(default=None, ge=0)
    avg_forks: Optional[float] = Field(default=None, ge=0)

    model_config = {"extra": "forbid"}


class OverallStats(BaseModel):
    """Global repository metrics."""

    github_repos: int = Field(ge=0)
    total_stars: int = Field(ge=0)
    total_forks: int = Field(ge=0)
    max_stars: int = Field(ge=0)
    max_forks: int = Field(ge=0)
    zenodo_repos: int = Field(ge=0)
    total_views: int = Field(ge=0)
    total_downloads: int = Field(ge=0)
    avg_stars: float = Field(ge=0)
    avg_forks: float = Field(ge=0)
    last_updated: str = Field(description="ISO 8601 timestamp.")

    model_config = {"extra": "forbid"}


class RepoStatsSummary(BaseModel):
    """Aggregated repository metrics for the Jekyll site.

    Written as ``repo_stats.yml`` in ``_data/``.
    """

    overall: OverallStats
    by_conference: list[ConferenceRepoStats]
    by_year: list[YearRepoStats]

    model_config = {"extra": "forbid"}
