"""Summary statistics schema.

Generated by ``generate_statistics.py`` → ``summary.yml``.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class Summary(BaseModel):
    """High-level summary statistics for the Jekyll site.

    Written as ``summary.yml`` in ``_data/``.
    """

    schema_version: str = Field(description="Semantic version of the data schema bundle.")
    total_artifacts: int = Field(ge=0, description="Total number of artifacts across all conferences.")
    total_conferences: int = Field(ge=0, description="Total number of tracked conferences.")
    systems_artifacts: int = Field(ge=0, description="Artifacts from systems conferences.")
    security_artifacts: int = Field(ge=0, description="Artifacts from security conferences.")
    conferences_list: list[str] = Field(description="List of all tracked conference abbreviations.")
    systems_conferences: list[str] = Field(description="List of systems conference abbreviations.")
    security_conferences: list[str] = Field(description="List of security conference abbreviations.")
    year_range: str = Field(pattern=r"^\d{4}-\d{4}$", description="Range of years covered in 'YYYY-YYYY' format.")
    last_updated: str = Field(description="ISO 8601 UTC timestamp of last data update.")

    model_config = {"extra": "forbid"}
