"""Top repository schema.

Generated by ``generate_repo_stats.py`` → ``top_repos.json``.
Variants: ``systems_top_repos.json``, ``security_top_repos.json``.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class TopRepo(BaseModel):
    """Top-ranked artifact repository by GitHub stars, with paper metadata and activity info."""

    title: str = Field(description="Paper title associated with this repository.")
    url: str = Field(description="GitHub repository URL.")
    year: int = Field(description="Publication year.")
    stars: int = Field(ge=0, description="GitHub star count.")
    forks: int = Field(ge=0, description="GitHub fork count.")
    authors: str = Field(description="Comma-separated author names.")
    github_org: str = Field(default="", description="GitHub organization or user.")
    badges: str = Field(default="", description="Comma-separated badge names.")
    last_active: str = Field(default="", description="Last activity date (YYYY-MM format).")
    description: str = Field(default="", description="Repository description.")
    language: str = Field(default="", description="Primary programming language.")
    conference: str = Field(description="Conference where the artifact was published.")
    area: str = Field(description="Research area: 'systems' or 'security'.")

    model_config = {"extra": "forbid"}
